name: gwasi-extractor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.31.0
  - pandas>=2.0.0
  - praw>=7.7.1
  - python-dotenv>=1.0.0
  - pip
  - pip:
    - argparse