name: CultureDataAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - polars>=1.31.0
  - numpy
  - pandas
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - python-dotenv
  - psycopg2
  - requests
  - pip
  - pip:
      - stashapp-tools
      - python-levenshtein
      - rapidfuzz
