services:
  db:
    image: postgres:18.0
    restart: always
    ports:
      - 5434:5432
    volumes:
      - db_vol:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DATABASE}'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  db_vol:
